### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by kaigon** [matthewbdaly/grunt-mini-static-blog#2]
I used the **`"npm install grunt-mini-static-blog --save-dev"`** install method but keep getting the error that this plugin is not published in the npm registry. Here's the debug.log if that helps: 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'grunt-mini-static-blog',
1 verbose cli   '--save-dev' ]
2 info using npm@3.3.12
3 info using node@v5.1.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData grunt-mini-static-blog
8 silly fetchNamedPackageData grunt-mini-static-blog
9 silly mapToRegistry name grunt-mini-static-blog
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/grunt-mini-static-blog
13 verbose request uri https://registry.npmjs.org/grunt-mini-static-blog
14 verbose request no auth needed
15 info attempt registry request try #1 at 2:52:26 PM
16 verbose request id dc27eed171367e7f
17 http request GET https://registry.npmjs.org/grunt-mini-static-blog
18 http 404 https://registry.npmjs.org/grunt-mini-static-blog
19 verbose headers { 'content-type': 'application/json',
19 verbose headers   'cache-control': 'max-age=0',
19 verbose headers   'content-length': '2',
19 verbose headers   'accept-ranges': 'bytes',
19 verbose headers   date: 'Mon, 28 Dec 2015 20:52:25 GMT',
19 verbose headers   via: '1.1 varnish',
19 verbose headers   age: '0',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'x-served-by': 'cache-dfw1826-DFW',
19 verbose headers   'x-cache': 'MISS',
19 verbose headers   'x-cache-hits': '0',
19 verbose headers   'x-timer': 'S1451335945.926998,VS0,VE71' }
20 silly get cb [ 404,
20 silly get   { 'content-type': 'application/json',
20 silly get     'cache-control': 'max-age=0',
20 silly get     'content-length': '2',
20 silly get     'accept-ranges': 'bytes',
20 silly get     date: 'Mon, 28 Dec 2015 20:52:25 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     age: '0',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-dfw1826-DFW',
20 silly get     'x-cache': 'MISS',
20 silly get     'x-cache-hits': '0',
20 silly get     'x-timer': 'S1451335945.926998,VS0,VE71' } ]
21 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/grunt-mini-static-blog
21 silly fetchPackageMetaData     at makeError (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
21 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:242:14)
21 silly fetchPackageMetaData     at Request._callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
21 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
21 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
21 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
21 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1082:10)
21 silly fetchPackageMetaData     at emitOne (events.js:82:20)
21 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
21 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1009:12)
21 silly fetchPackageMetaData  error for grunt-mini-static-blog { [Error: Registry returned 404 for GET on https://registry.npmjs.org/grunt-mini-static-blog]
21 silly fetchPackageMetaData   pkgid: 'grunt-mini-static-blog',
21 silly fetchPackageMetaData   statusCode: 404,
21 silly fetchPackageMetaData   code: 'E404' }
22 silly rollbackFailedOptional Starting
23 silly rollbackFailedOptional Finishing
24 silly runTopLevelLifecycles Starting
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/grunt-mini-static-blog
27 verbose stack     at makeError (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:242:14)
27 verbose stack     at Request._callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
27 verbose stack     at Request.self.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
27 verbose stack     at emitTwo (events.js:87:13)
27 verbose stack     at Request.emit (events.js:172:7)
27 verbose stack     at Request.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1082:10)
27 verbose stack     at emitOne (events.js:82:20)
27 verbose stack     at Request.emit (events.js:169:7)
27 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1009:12)
28 verbose statusCode 404
29 verbose pkgid grunt-mini-static-blog
30 verbose cwd C:\Users\Justin\Desktop\repos\chipmunkbay
31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-mini-static-blog" "--save-dev"
33 error node v5.1.1
34 error npm  v3.3.12
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/grunt-mini-static-blog
36 error 404
36 error 404 'grunt-mini-static-blog' is not in the npm registry.
36 error 404 You should bug the author to publish it (or use the name yourself!)
36 error 404
36 error 404 Note that you can also install from a
36 error 404 tarball, folder, http url, or git url.
37 verbose exit [ 1, true ]
```

**Comment by matthewbdaly** [comment]
This was never published to NPM. The reason is that it's a cut-down version of grunt-blogbuilder, written solely for a tutorial. I use grunt-blogbuilder for my own site, which is also my own work, and is on NPM.

**Comment by matthewbdaly** [comment]
I probably ought to update the README to reflect this as the one generated doesn't make that clear.

**Comment by matthewbdaly** [comment]
I recommend using grunt-blogbuilder instead as it's essentially just a more featureful version of this. Or you can fork this, amend it to your liking and publish it on NPM yourself.

**Comment by matthewbdaly** [comment]
Or, you can install it direct from the Github http URL

**Comment by kaigon** [comment]
Sounds good. Many thanks!
